// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: ssh-signer.proto

package ssh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Certificate request message.
type SSHCertificateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Public key to sign
	Public string `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	// hostname to sign
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	User     string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// Optional: requested certificate validity period, in seconds.
	ValidityDuration int64 `protobuf:"varint,4,opt,name=validity_duration,json=validityDuration,proto3" json:"validity_duration,omitempty"`
}

func (x *SSHCertificateRequest) Reset() {
	*x = SSHCertificateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssh_signer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSHCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHCertificateRequest) ProtoMessage() {}

func (x *SSHCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ssh_signer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHCertificateRequest.ProtoReflect.Descriptor instead.
func (*SSHCertificateRequest) Descriptor() ([]byte, []int) {
	return file_ssh_signer_proto_rawDescGZIP(), []int{0}
}

func (x *SSHCertificateRequest) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *SSHCertificateRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SSHCertificateRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SSHCertificateRequest) GetValidityDuration() int64 {
	if x != nil {
		return x.ValidityDuration
	}
	return 0
}

// Certificate response message.
type SSHCertificateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Root string `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
}

func (x *SSHCertificateResponse) Reset() {
	*x = SSHCertificateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssh_signer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSHCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHCertificateResponse) ProtoMessage() {}

func (x *SSHCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ssh_signer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHCertificateResponse.ProtoReflect.Descriptor instead.
func (*SSHCertificateResponse) Descriptor() ([]byte, []int) {
	return file_ssh_signer_proto_rawDescGZIP(), []int{1}
}

func (x *SSHCertificateResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SSHCertificateResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SSHCertificateResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

var File_ssh_signer_proto protoreflect.FileDescriptor

var file_ssh_signer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x73, 0x68, 0x2d, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x73, 0x73, 0x68, 0x22, 0x8c, 0x01, 0x0a, 0x15, 0x53, 0x53, 0x48, 0x43,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x54, 0x0a, 0x16, 0x53, 0x53, 0x48, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x32, 0x67, 0x0a, 0x15,
	0x53, 0x53, 0x48, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x73, 0x68,
	0x2e, 0x53, 0x53, 0x48, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x73, 0x68, 0x2e, 0x53, 0x53, 0x48,
	0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x6d, 0x2f, 0x69, 0x73, 0x74, 0x69,
	0x6f, 0x64, 0x2f, 0x73, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ssh_signer_proto_rawDescOnce sync.Once
	file_ssh_signer_proto_rawDescData = file_ssh_signer_proto_rawDesc
)

func file_ssh_signer_proto_rawDescGZIP() []byte {
	file_ssh_signer_proto_rawDescOnce.Do(func() {
		file_ssh_signer_proto_rawDescData = protoimpl.X.CompressGZIP(file_ssh_signer_proto_rawDescData)
	})
	return file_ssh_signer_proto_rawDescData
}

var file_ssh_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ssh_signer_proto_goTypes = []interface{}{
	(*SSHCertificateRequest)(nil),  // 0: ssh.SSHCertificateRequest
	(*SSHCertificateResponse)(nil), // 1: ssh.SSHCertificateResponse
}
var file_ssh_signer_proto_depIdxs = []int32{
	0, // 0: ssh.SSHCertificateService.CreateCertificate:input_type -> ssh.SSHCertificateRequest
	1, // 1: ssh.SSHCertificateService.CreateCertificate:output_type -> ssh.SSHCertificateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ssh_signer_proto_init() }
func file_ssh_signer_proto_init() {
	if File_ssh_signer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ssh_signer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSHCertificateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssh_signer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSHCertificateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ssh_signer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ssh_signer_proto_goTypes,
		DependencyIndexes: file_ssh_signer_proto_depIdxs,
		MessageInfos:      file_ssh_signer_proto_msgTypes,
	}.Build()
	File_ssh_signer_proto = out.File
	file_ssh_signer_proto_rawDesc = nil
	file_ssh_signer_proto_goTypes = nil
	file_ssh_signer_proto_depIdxs = nil
}
