// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ssh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SSHCertificateServiceClient is the client API for SSHCertificateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SSHCertificateServiceClient interface {
	CreateCertificate(ctx context.Context, in *SSHCertificateRequest, opts ...grpc.CallOption) (*SSHCertificateResponse, error)
}

type sSHCertificateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSSHCertificateServiceClient(cc grpc.ClientConnInterface) SSHCertificateServiceClient {
	return &sSHCertificateServiceClient{cc}
}

func (c *sSHCertificateServiceClient) CreateCertificate(ctx context.Context, in *SSHCertificateRequest, opts ...grpc.CallOption) (*SSHCertificateResponse, error) {
	out := new(SSHCertificateResponse)
	err := c.cc.Invoke(ctx, "/ssh.SSHCertificateService/CreateCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SSHCertificateServiceServer is the server API for SSHCertificateService service.
// All implementations must embed UnimplementedSSHCertificateServiceServer
// for forward compatibility
type SSHCertificateServiceServer interface {
	CreateCertificate(context.Context, *SSHCertificateRequest) (*SSHCertificateResponse, error)
	mustEmbedUnimplementedSSHCertificateServiceServer()
}

// UnimplementedSSHCertificateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSSHCertificateServiceServer struct {
}

func (UnimplementedSSHCertificateServiceServer) CreateCertificate(context.Context, *SSHCertificateRequest) (*SSHCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCertificate not implemented")
}
func (UnimplementedSSHCertificateServiceServer) mustEmbedUnimplementedSSHCertificateServiceServer() {}

// UnsafeSSHCertificateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SSHCertificateServiceServer will
// result in compilation errors.
type UnsafeSSHCertificateServiceServer interface {
	mustEmbedUnimplementedSSHCertificateServiceServer()
}

func RegisterSSHCertificateServiceServer(s grpc.ServiceRegistrar, srv SSHCertificateServiceServer) {
	s.RegisterService(&SSHCertificateService_ServiceDesc, srv)
}

func _SSHCertificateService_CreateCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSHCertificateServiceServer).CreateCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.SSHCertificateService/CreateCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSHCertificateServiceServer).CreateCertificate(ctx, req.(*SSHCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SSHCertificateService_ServiceDesc is the grpc.ServiceDesc for SSHCertificateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SSHCertificateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ssh.SSHCertificateService",
	HandlerType: (*SSHCertificateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCertificate",
			Handler:    _SSHCertificateService_CreateCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssh-signer.proto",
}
