
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns
subjects:
  - kind: ServiceAccount
    name: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
# Needs to list namespaces - even if no permission
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
