---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istiod
  namespace: istio-system
  labels:
    release: istiod
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istiod
  namespace: istio-system
  labels:
    release: istiod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istiod
      release: istiod
---
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
  labels:
    release: istiod
spec:
  ports:
    - port: 443
      name: https-inject
      targetPort: 15017
    - port: 15010
      name: http2-xds # direct
    - port: 15011
      name: https-xds-spifeecert # mTLS
    - port: 15012
      name: https-xds-dnscert # mTLS
    - port: 8080
      name: http-legacy-discovery # direct
    - port: 15014
      name: http-monitoring
  selector:
    app: istiod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istiod
    release: istiod
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: istiod
  template:
    metadata:
      labels:
        app: istiod
        istio: pilot
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istiod
      containers:
        - name: discovery
          image: gcr.io/costin-istio/pilot:latest
          #image: gcr.io/costin-istio/istiod:latest
          #image: gcr.io/istio-testing/istiod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 15010
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
          # Args used by pilot - istiod doesn't use args.
          args:
            - "discovery"
            - --secureGrpcAddr
            - ""
          envFrom:
          - configMapRef:
              name: istiod
              optional: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CONFIG_NAMESPACE
              value: istio-system
            - name: WEBHOOK
              value: istiod
          resources:
            requests:
              cpu: 800m
              memory: 2048Mi
          volumeMounts:
            # For backward compat, if secrets already exists. Currently not used/implemented
            # Instead shifting traffic to istiod
            - name: istio-certs
              mountPath: /var/run/secrets/istio
              readOnly: true
            # Technically not needed on this pod - but it helps debugging/testing SDS
            # Should be removed after everything works.
            - name: istio-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
            - name: local-certs
              mountPath: /var/run/secrets/istio-dns
            - name: cacerts
              mountPath: /etc/cacerts
              readOnly: true
            - name: galley
              mountPath: /var/lib/istio/galley
              readOnly: true
            - name: mesh
              mountPath: /etc/istio/config
              readOnly: true
            - name: inject
              mountPath: /var/lib/istio/inject
              readOnly: true
            - name: istiod
              mountPath: /var/lib/istio/local
              readOnly: true
      securityContext:
        # Temp, for debugging (need to install tools, etc)
        runAsUser: 0
        runAsGroup: 1337
      volumes:
        - emptyDir:
            medium: Memory
          name: local-certs
        - name: istio-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: istio-ca
                  expirationSeconds: 43200
                  path: istio-token
        - name: istio-certs
          secret:
            secretName: istio.istio-pilot-service-account
            optional: true
        - name: istiod
          configMap:
            name: istiod
            optional: true
        # Optional: user-generated root
        - name: cacerts
          secret:
            secretName: cacerts
            optional: true
        # Optional - image should have
        - name: inject
          configMap:
            name: inject
            optional: true
        - name: values
          configMap:
            name: values
            optional: true
        - name: mesh
          configMap:
            name: istiod-mesh
            optional: true
        - name: galley
          configMap:
            name: istiod-galley
            optional: true
